"""session exercise planned targets

Revision ID: 0d980e778955
Revises: 4be59d7eb508
Create Date: 2026-06-29 13:57:32.561859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d980e778955'
down_revision: Union[str, Sequence[str], None] = '4be59d7eb508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_exercises', sa.Column('target_sets', sa.Integer(), nullable=True))
    op.add_column('session_exercises', sa.Column('target_reps_min', sa.Integer(), nullable=True))
    op.add_column('session_exercises', sa.Column('target_reps_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_exercises', 'target_reps_max')
    op.drop_column('session_exercises', 'target_reps_min')
    op.drop_column('session_exercises', 'target_sets')
    # ### end Alembic commands ###
