"""set side-rows and is_warmup

Revision ID: 4be59d7eb508
Revises: 834b69c7d3e4
Create Date: 2026-06-29 13:35:43.438531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4be59d7eb508'
down_revision: Union[str, Sequence[str], None] = '834b69c7d3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_logs', sa.Column('side', sa.String(), server_default='both', nullable=False))
    op.add_column('set_logs', sa.Column('is_warmup', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('set_logs', 'weight_kg_left')
    op.drop_column('set_logs', 'weight_kg_right')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_logs', sa.Column('weight_kg_right', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('set_logs', sa.Column('weight_kg_left', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('set_logs', 'is_warmup')
    op.drop_column('set_logs', 'side')
    # ### end Alembic commands ###
