"""add fk indexes

Revision ID: 834b69c7d3e4
Revises: 2d26f26a60ad
Create Date: 2026-06-29 13:24:50.367221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834b69c7d3e4'
down_revision: Union[str, Sequence[str], None] = '2d26f26a60ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bodyweight_logs_user_id'), 'bodyweight_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_exercise_muscles_exercise_id'), 'exercise_muscles', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_muscles_muscle_group_id'), 'exercise_muscles', ['muscle_group_id'], unique=False)
    op.create_index(op.f('ix_program_days_program_id'), 'program_days', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_exercises_exercise_id'), 'program_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_program_exercises_program_day_id'), 'program_exercises', ['program_day_id'], unique=False)
    op.create_index(op.f('ix_programs_user_id'), 'programs', ['user_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_exercise_id'), 'session_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_set_logs_session_exercise_id'), 'set_logs', ['session_exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_logs_session_exercise_id'), table_name='set_logs')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_session_exercises_exercise_id'), table_name='session_exercises')
    op.drop_index(op.f('ix_programs_user_id'), table_name='programs')
    op.drop_index(op.f('ix_program_exercises_program_day_id'), table_name='program_exercises')
    op.drop_index(op.f('ix_program_exercises_exercise_id'), table_name='program_exercises')
    op.drop_index(op.f('ix_program_days_program_id'), table_name='program_days')
    op.drop_index(op.f('ix_exercise_muscles_muscle_group_id'), table_name='exercise_muscles')
    op.drop_index(op.f('ix_exercise_muscles_exercise_id'), table_name='exercise_muscles')
    op.drop_index(op.f('ix_bodyweight_logs_user_id'), table_name='bodyweight_logs')
    # ### end Alembic commands ###
